/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as ConnectorsIndexRouteImport } from './routes/connectors/index'
import { Route as ConnectorsConnectorIdRouteImport } from './routes/connectors/$connectorId'
import { Route as InboxIndexRouteImport } from './routes/inbox/index'
import { Route as InboxTaskIdRouteImport } from './routes/inbox/$taskId'
import { Route as RulesIndexRouteImport } from './routes/rules/index'
import { Route as RulesRuleIdRouteImport } from './routes/rules/$ruleId'
import { Route as RulesNewRouteImport } from './routes/rules/new'
import { Route as ApiConnectorsConnectorIdAuthorizeRouteImport } from './routes/api/connectors/$connectorId/authorize'
import { Route as ApiConnectorsConnectorIdCallbackRouteImport } from './routes/api/connectors/$connectorId/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsIndexRoute = ConnectorsIndexRouteImport.update({
  id: '/connectors/',
  path: '/connectors/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsConnectorIdRoute = ConnectorsConnectorIdRouteImport.update({
  id: '/connectors/$connectorId',
  path: '/connectors/$connectorId',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxIndexRoute = InboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxTaskIdRoute = InboxTaskIdRouteImport.update({
  id: '/inbox/$taskId',
  path: '/inbox/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesIndexRoute = RulesIndexRouteImport.update({
  id: '/rules/',
  path: '/rules/',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRuleIdRoute = RulesRuleIdRouteImport.update({
  id: '/rules/$ruleId',
  path: '/rules/$ruleId',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesNewRoute = RulesNewRouteImport.update({
  id: '/rules/new',
  path: '/rules/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConnectorsConnectorIdAuthorizeRoute =
  ApiConnectorsConnectorIdAuthorizeRouteImport.update({
    id: '/api/connectors/$connectorId/authorize',
    path: '/api/connectors/$connectorId/authorize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiConnectorsConnectorIdCallbackRoute =
  ApiConnectorsConnectorIdCallbackRouteImport.update({
    id: '/api/connectors/$connectorId/callback',
    path: '/api/connectors/$connectorId/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connectors/$connectorId': typeof ConnectorsConnectorIdRoute
  '/inbox/$taskId': typeof InboxTaskIdRoute
  '/rules/$ruleId': typeof RulesRuleIdRoute
  '/rules/new': typeof RulesNewRoute
  '/agents/': typeof AgentsIndexRoute
  '/connectors/': typeof ConnectorsIndexRoute
  '/inbox/': typeof InboxIndexRoute
  '/rules/': typeof RulesIndexRoute
  '/api/connectors/$connectorId/authorize': typeof ApiConnectorsConnectorIdAuthorizeRoute
  '/api/connectors/$connectorId/callback': typeof ApiConnectorsConnectorIdCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connectors/$connectorId': typeof ConnectorsConnectorIdRoute
  '/inbox/$taskId': typeof InboxTaskIdRoute
  '/rules/$ruleId': typeof RulesRuleIdRoute
  '/rules/new': typeof RulesNewRoute
  '/agents': typeof AgentsIndexRoute
  '/connectors': typeof ConnectorsIndexRoute
  '/inbox': typeof InboxIndexRoute
  '/rules': typeof RulesIndexRoute
  '/api/connectors/$connectorId/authorize': typeof ApiConnectorsConnectorIdAuthorizeRoute
  '/api/connectors/$connectorId/callback': typeof ApiConnectorsConnectorIdCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connectors/$connectorId': typeof ConnectorsConnectorIdRoute
  '/inbox/$taskId': typeof InboxTaskIdRoute
  '/rules/$ruleId': typeof RulesRuleIdRoute
  '/rules/new': typeof RulesNewRoute
  '/agents/': typeof AgentsIndexRoute
  '/connectors/': typeof ConnectorsIndexRoute
  '/inbox/': typeof InboxIndexRoute
  '/rules/': typeof RulesIndexRoute
  '/api/connectors/$connectorId/authorize': typeof ApiConnectorsConnectorIdAuthorizeRoute
  '/api/connectors/$connectorId/callback': typeof ApiConnectorsConnectorIdCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connectors/$connectorId'
    | '/inbox/$taskId'
    | '/rules/$ruleId'
    | '/rules/new'
    | '/agents/'
    | '/connectors/'
    | '/inbox/'
    | '/rules/'
    | '/api/connectors/$connectorId/authorize'
    | '/api/connectors/$connectorId/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connectors/$connectorId'
    | '/inbox/$taskId'
    | '/rules/$ruleId'
    | '/rules/new'
    | '/agents'
    | '/connectors'
    | '/inbox'
    | '/rules'
    | '/api/connectors/$connectorId/authorize'
    | '/api/connectors/$connectorId/callback'
  id:
    | '__root__'
    | '/'
    | '/connectors/$connectorId'
    | '/inbox/$taskId'
    | '/rules/$ruleId'
    | '/rules/new'
    | '/agents/'
    | '/connectors/'
    | '/inbox/'
    | '/rules/'
    | '/api/connectors/$connectorId/authorize'
    | '/api/connectors/$connectorId/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectorsConnectorIdRoute: typeof ConnectorsConnectorIdRoute
  InboxTaskIdRoute: typeof InboxTaskIdRoute
  RulesRuleIdRoute: typeof RulesRuleIdRoute
  RulesNewRoute: typeof RulesNewRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  ConnectorsIndexRoute: typeof ConnectorsIndexRoute
  InboxIndexRoute: typeof InboxIndexRoute
  RulesIndexRoute: typeof RulesIndexRoute
  ApiConnectorsConnectorIdAuthorizeRoute: typeof ApiConnectorsConnectorIdAuthorizeRoute
  ApiConnectorsConnectorIdCallbackRoute: typeof ApiConnectorsConnectorIdCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors/': {
      id: '/connectors/'
      path: '/connectors'
      fullPath: '/connectors/'
      preLoaderRoute: typeof ConnectorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors/$connectorId': {
      id: '/connectors/$connectorId'
      path: '/connectors/$connectorId'
      fullPath: '/connectors/$connectorId'
      preLoaderRoute: typeof ConnectorsConnectorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/': {
      id: '/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof InboxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/$taskId': {
      id: '/inbox/$taskId'
      path: '/inbox/$taskId'
      fullPath: '/inbox/$taskId'
      preLoaderRoute: typeof InboxTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/': {
      id: '/rules/'
      path: '/rules'
      fullPath: '/rules/'
      preLoaderRoute: typeof RulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/$ruleId': {
      id: '/rules/$ruleId'
      path: '/rules/$ruleId'
      fullPath: '/rules/$ruleId'
      preLoaderRoute: typeof RulesRuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/new': {
      id: '/rules/new'
      path: '/rules/new'
      fullPath: '/rules/new'
      preLoaderRoute: typeof RulesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connectors/$connectorId/authorize': {
      id: '/api/connectors/$connectorId/authorize'
      path: '/api/connectors/$connectorId/authorize'
      fullPath: '/api/connectors/$connectorId/authorize'
      preLoaderRoute: typeof ApiConnectorsConnectorIdAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connectors/$connectorId/callback': {
      id: '/api/connectors/$connectorId/callback'
      path: '/api/connectors/$connectorId/callback'
      fullPath: '/api/connectors/$connectorId/callback'
      preLoaderRoute: typeof ApiConnectorsConnectorIdCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectorsConnectorIdRoute: ConnectorsConnectorIdRoute,
  InboxTaskIdRoute: InboxTaskIdRoute,
  RulesRuleIdRoute: RulesRuleIdRoute,
  RulesNewRoute: RulesNewRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  ConnectorsIndexRoute: ConnectorsIndexRoute,
  InboxIndexRoute: InboxIndexRoute,
  RulesIndexRoute: RulesIndexRoute,
  ApiConnectorsConnectorIdAuthorizeRoute:
    ApiConnectorsConnectorIdAuthorizeRoute,
  ApiConnectorsConnectorIdCallbackRoute: ApiConnectorsConnectorIdCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
