/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as ConnectorsIndexRouteImport } from './routes/connectors/index'
import { Route as ConnectorsConnectorIdRouteImport } from './routes/connectors/$connectorId'
import { Route as ApiConnectorsConnectorIdAuthorizeRouteImport } from './routes/api/connectors/$connectorId/authorize'
import { Route as ApiConnectorsConnectorIdCallbackRouteImport } from './routes/api/connectors/$connectorId/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsIndexRoute = ConnectorsIndexRouteImport.update({
  id: '/connectors/',
  path: '/connectors/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsConnectorIdRoute = ConnectorsConnectorIdRouteImport.update({
  id: '/connectors/$connectorId',
  path: '/connectors/$connectorId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConnectorsConnectorIdAuthorizeRoute =
  ApiConnectorsConnectorIdAuthorizeRouteImport.update({
    id: '/api/connectors/$connectorId/authorize',
    path: '/api/connectors/$connectorId/authorize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiConnectorsConnectorIdCallbackRoute =
  ApiConnectorsConnectorIdCallbackRouteImport.update({
    id: '/api/connectors/$connectorId/callback',
    path: '/api/connectors/$connectorId/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connectors/$connectorId': typeof ConnectorsConnectorIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/connectors/': typeof ConnectorsIndexRoute
  '/api/connectors/$connectorId/authorize': typeof ApiConnectorsConnectorIdAuthorizeRoute
  '/api/connectors/$connectorId/callback': typeof ApiConnectorsConnectorIdCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connectors/$connectorId': typeof ConnectorsConnectorIdRoute
  '/agents': typeof AgentsIndexRoute
  '/connectors': typeof ConnectorsIndexRoute
  '/api/connectors/$connectorId/authorize': typeof ApiConnectorsConnectorIdAuthorizeRoute
  '/api/connectors/$connectorId/callback': typeof ApiConnectorsConnectorIdCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connectors/$connectorId': typeof ConnectorsConnectorIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/connectors/': typeof ConnectorsIndexRoute
  '/api/connectors/$connectorId/authorize': typeof ApiConnectorsConnectorIdAuthorizeRoute
  '/api/connectors/$connectorId/callback': typeof ApiConnectorsConnectorIdCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connectors/$connectorId'
    | '/agents/'
    | '/connectors/'
    | '/api/connectors/$connectorId/authorize'
    | '/api/connectors/$connectorId/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connectors/$connectorId'
    | '/agents'
    | '/connectors'
    | '/api/connectors/$connectorId/authorize'
    | '/api/connectors/$connectorId/callback'
  id:
    | '__root__'
    | '/'
    | '/connectors/$connectorId'
    | '/agents/'
    | '/connectors/'
    | '/api/connectors/$connectorId/authorize'
    | '/api/connectors/$connectorId/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectorsConnectorIdRoute: typeof ConnectorsConnectorIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  ConnectorsIndexRoute: typeof ConnectorsIndexRoute
  ApiConnectorsConnectorIdAuthorizeRoute: typeof ApiConnectorsConnectorIdAuthorizeRoute
  ApiConnectorsConnectorIdCallbackRoute: typeof ApiConnectorsConnectorIdCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors/': {
      id: '/connectors/'
      path: '/connectors'
      fullPath: '/connectors/'
      preLoaderRoute: typeof ConnectorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors/$connectorId': {
      id: '/connectors/$connectorId'
      path: '/connectors/$connectorId'
      fullPath: '/connectors/$connectorId'
      preLoaderRoute: typeof ConnectorsConnectorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connectors/$connectorId/authorize': {
      id: '/api/connectors/$connectorId/authorize'
      path: '/api/connectors/$connectorId/authorize'
      fullPath: '/api/connectors/$connectorId/authorize'
      preLoaderRoute: typeof ApiConnectorsConnectorIdAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connectors/$connectorId/callback': {
      id: '/api/connectors/$connectorId/callback'
      path: '/api/connectors/$connectorId/callback'
      fullPath: '/api/connectors/$connectorId/callback'
      preLoaderRoute: typeof ApiConnectorsConnectorIdCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectorsConnectorIdRoute: ConnectorsConnectorIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  ConnectorsIndexRoute: ConnectorsIndexRoute,
  ApiConnectorsConnectorIdAuthorizeRoute:
    ApiConnectorsConnectorIdAuthorizeRoute,
  ApiConnectorsConnectorIdCallbackRoute: ApiConnectorsConnectorIdCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
